[build]
builder = "nixpacks"

[deploy]
preDeploy = "npm run db:push"
startCommand = "npm run start"
healthcheckPath = "/live"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = { default = "5000" }

# Railway will automatically provide DATABASE_URL when PostgreSQL service is connected
# You need to set these in Railway dashboard:
# FIREBASE_PROJECT_ID
# FIREBASE_CLIENT_EMAIL  
# FIREBASE_PRIVATE_KEY
# OPENAI_API_KEY
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET

[experimental]
incrementalBuilds = true

[nixpacks]
# Optimize for Node.js production
staticDir = "./dist/public"

[nixpacks.variables]
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"